WorldGen:
    num_objs: 30

    #Models Types (fixed inertia): box (0),   brick (1),    woodplat1 (1)

    models: ["brick", "box"]
    fixed_inertia: [1, 0]

    wall:
        offset_dist: 2.4
        use_walls: true
        thickness: 0.35

    
    pos:
        min: [1.1, -2.2, 0]
        max: [4.5, 2.2, 0]
    
    dim:
        min: [0.1, 0.05, 0.1]
        max: [0.5, 0.45, 0.2]
    
    rpy:
        min: [0, 0, -3.14]
        max: [0, 0, 3.14]

    #mass:
        #min: 0.5
        #max: 15
    
