WorldGen:
    num_objs: 45

    #Models Types (fixed inertia):
        # box (0)
        # brick (1)
        # woodplat1 (1)
        # woodpallet1 (1)
        # wood_crate1 (1)
        # wood_crate2_small (1)
        # wood_crate3_long (1)
        # stair1 (1)

    models: ["brick", "box", "wood_crate3_long", "woodplat1", "woodpallet1", "wood_crate1", "wood_crate2_small", "stair1", "brickpile1", "wood_crate4"]
    fixed_inertia: [1, 0, 1, 1, 1, 1, 1, 1, 1, 1]
    max_instances: [-1, 10, 0, 1, 1, 1, 2, 0, 0, 0]  #maximum number of objects per class. -1 means no limits

    wall:
        offset_dist: 2.4
        use_walls: true
        thickness: 0.35

    pos:
        min: [1.2, -3, 0]
        max: [5.5, 3, 0]

    dim:
        min: [0.20, 0.20, 0.1]
        max: [0.70, 0.40, 0.25]

    rpy:
        min: [-1.6, -1.6, -3.14]
        max: [1.6, 1.6, 3.14]

    #mass:
        #min: 0.5
        #max: 15

