WorldGen:
    num_objs: 25

    #Models Types (fixed inertia):
        # box (0)
        # brick (1)
        # woodplat1 (1)
        # woodpallet1 (1)
        # wood_crate1 (1)
        # wood_crate2_small (1)
        # wood_crate3_long (1)

    models: ["brick", "box", "wood_crate3_long", "woodplat1", "woodpallet1", "wood_crate1", "wood_crate2_small"]
    fixed_inertia: [1, 0, 1, 1, 1, 1, 1]
    max_instances: [-1, -1, 0, 2, 0, 1, 5]  #maximum number of objects per class. -1 means no limits

    wall:
        offset_dist: 2.4
        use_walls: true
        thickness: 0.35

    pos:
        min: [1.2, -2.2, 0]
        max: [4.5, 2.2, 0]
    
    dim:
        min: [0.25, 0.20, 0.1]
        max: [0.50, 0.45, 0.25]
    
    rpy:
        min: [0, 0, -3.14]
        max: [0, 0, 3.14]

    #mass:
        #min: 0.5
        #max: 15
    
