WorldGen:
    num_objs: 35

    #models: ["box"]

    wall:
        offset_dist: 2.4
        use_walls: true
        thickness: 0.35

    
    pos:
        min: [1.1, -2.0, 0]
        max: [4.5, 2.0, 0]
    
    dim:
        min: [0.075, 0.05, 0.1]
        max: [0.35, 0.3, 0.2]
    
    rpy:
        min: [0, 0, -3.14]
        max: [0, 0, 3.14]

    #mass:
        #min: 0.5
        #max: 15
    
